apiVersion: v1
kind: ConfigMap
metadata:
  name: turbokube
data:
  config.json: |
    {
      "cpu": "2",
      "memory": "64Gi",
      "pods": "1024"
    }
  apiserver.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDjDCCAnSgAwIBAgIIVpSJz1x/2L8wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yNTExMDUxNDM4MDdaFw0yNjExMDUxNDQzMDdaMBkx
    FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEAuH9AwUftY2OWeI0BuE/Dsurx1gONQC1D8Xtny+7UYp76k4Kp4uH9
    fU8qIgC1Byth9mAVCOx2iiqA9Di7N7/IW6hq+b0i5D31v7N2NGbn6OnjhXZMZPxd
    9Ow8IlZAh5WoxomBZDoSVkCNPddVo5nbHANpwZBRExkjexjBwZ0GYTiEDF1ixuop
    RXT2Jr2HJRijUeiIOQyBvqZfLci5hrJwdE+W6Y8z+sd7s8t4G/k4T1WQjq5xmABr
    d23us7iFz0gYlaIcKUVCe3IRDNIuVOJpvCl8WXfPZ675D0ELZsdZ9KvKG7O7B9Mw
    g8ZK09XhjrDQ1jrtbFbiJlCK/OD1HwZ8vQIDAQABo4HbMIHYMA4GA1UdDwEB/wQE
    AwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
    MBaAFEECi6hnSdpdKKG8H1TO9RlRJu07MIGBBgNVHREEejB4ggZrdWJlLTCCCmt1
    YmVybmV0ZXOCEmt1YmVybmV0ZXMuZGVmYXVsdIIWa3ViZXJuZXRlcy5kZWZhdWx0
    LnN2Y4Ika3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FshwQKYAAB
    hwQKAAAahwQKAAATMA0GCSqGSIb3DQEBCwUAA4IBAQAV7lSJGpxPnj8cafBNNtIA
    mSB1K5U3kxf9WCmMXp12ZQR0fYk5DBr7UgWf/hUAdfdp8UUCWexyzPIWgpQ2G9vk
    ILPJIQsko6x2hm6JamRlfKFHYp5Rg0wsXmYJ28GNKE/7xclCoDZtn3+YMNAK+66J
    4lt7BjV8YjbCjQYdzIQV37isjCkSHxcm7VGNksZYwZC7gGJnP+WWqahGLhrZhRQS
    ssoDlXnzvWguutuflA7k0sLQjPEGWHAh2z7S4z0uLtmiL5lrZbrQ4wlkdY9W/Eox
    svNcZPNf0pepPO46fhLthiskFmbrq5F2ncjJJjjzAkqiEZYvhuwT8EexTQz+tAwR
    -----END CERTIFICATE-----
  apiserver.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAuH9AwUftY2OWeI0BuE/Dsurx1gONQC1D8Xtny+7UYp76k4Kp
    4uH9fU8qIgC1Byth9mAVCOx2iiqA9Di7N7/IW6hq+b0i5D31v7N2NGbn6OnjhXZM
    ZPxd9Ow8IlZAh5WoxomBZDoSVkCNPddVo5nbHANpwZBRExkjexjBwZ0GYTiEDF1i
    xuopRXT2Jr2HJRijUeiIOQyBvqZfLci5hrJwdE+W6Y8z+sd7s8t4G/k4T1WQjq5x
    mABrd23us7iFz0gYlaIcKUVCe3IRDNIuVOJpvCl8WXfPZ675D0ELZsdZ9KvKG7O7
    B9Mwg8ZK09XhjrDQ1jrtbFbiJlCK/OD1HwZ8vQIDAQABAoIBAAdNzl/4e37kSegy
    2N8VlU9HetR4poZkZFyygHzz0wemeJAPa69WOAVWdXoMIh6LCqFI03xbdCPrI9jH
    SC4gUwvB4p5JbRCxHUH+Fk9jxYmUfNPjR4n17bhNA+JuHLbhZ2GYvv0bSW+Ntam9
    lR/ZbvGwdubZUkRZyexNIhqKn16I32ZuUQHk/MqHI9W6oyNFIWGzP37W8PC+YzH/
    q1my36dDI0H+DmH8EWtctodj77yQAfSJjs1aQVm89nkQRSpQ4poWZMyL63JqPmfX
    PtAZCuVkoNslZ4qj0vlInid+mUi9m4GyAtGkZDoZYnqNnpJ1Jc1q1wxPw42mnApk
    zg7XZXcCgYEA9f2EXWOIRNaraxh3nRX0YQA8djfXbcqQ3qV3jKJ4l0QnyT+TA8xz
    0ve3VPNP5p+a5cnDOn3Th5zqdJr8Cb/awY5qWa6gmmgiV/X0p9B/gWVsb6AtauN7
    eX9dHTwEWa9uR0tdoJ64ePln/i73Sdcg8xLmik0Xis7XpKsNiAv+ml8CgYEAwAEp
    GRn444sQJ8HOcBAA0kuwlwDq5kza2T+PpgWz0cZA6bkM+XbasueURXxi9GTQeLCK
    x+jiRnmjRvuaxCFhT27rsjRRrO00tH4of+v0fwPBHrQ7ktZ0weg9lBHr0rNd8vjW
    t+wqw4ek10gouyHO5BJNFskgeIDZLteKEco3dmMCgYBC3yBUovIwhIslGgmqUoWU
    uRO2r4eI+UBYxnKxcJmHxadrNjUpGzOBboYQOfTGpSzeuvKvu/T9MNMrz9YkcFtv
    st+GccqHLzfm4Z4Y4L1I1+GaltjB7gVrCgyuHdqw5tf72akiOQO9H0/98ZaYJDt4
    2PKDNmHoAkLtKPMMwPX90QKBgFbCr32GPO8lMaGlc9Ezigt85Ej3wy1Z4TJ2BEUz
    InRSL5btZa18RYq+FkPn1xc0TveaXrvCwiyyXlN+8gpaQwyPxLV76sRHU5+Tul1D
    k/GpEqT7MEhD2/KbLOgxyOwm3Pcj9nKZpyE/s/8LvkwBFOn+UxNOwvtwzbLa9qrf
    Q3ydAoGBAKCD/EW5UIRYJF+ufdeH3sCbaMP1J7YQZYIoWrYOs6KODGjt82HAeEgW
    BhcwpkIeCyyLbKg8om/2g6Sq3axCTX7Lg8W6h7w/B2ER0XuGr4n1sF4HWEMLxje2
    ELhkE+HlCjf17SREorRyUtriQ8+t9aVQtyEXlgxIyY4EsrpfV/By
    -----END RSA PRIVATE KEY-----
  kubelet.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQnZQT251T0tOZVV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1EVXhORE00TURkYUZ3MHpOVEV4TURNeE5EUXpNRGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURJcEtXbDVvT1FFdE1aRmtOT0xSRlJ2MEZhOXFjT1FPRFBjUmxvYXVoOFFWejhjZ2NMYmVHVk9TRVoKUzdGdU5FbzdlRG9Hc0M0SlpsdjRyWm9aNURrcDJLUVBsOFF5TFkwUEFQbEpGOU5oQWpmWU5pWU1oRkxqQStHdApLTENpWi9pdHNYM3EvenNtYklTbjF6UmlWYWVjNVVKc3dVYXRrU2c5bksxQTlhaEpZcHJZNm5aUGpZOVB5SG12ClJ2OHFPa2d0SldscjBmc2ZMYXVJSktiVUt4MEpCeG1mSDVqai8reGFHRzNsSU13OFN3SjFURlM2bFBhZkQyM08KRjM4SW9FY2xsYStrZjIvYjJGWUZXeVZ4c1FDdlNBRUpQaTRLbVFQMHlvSjJTUUFKZ0RCMHp6dlR3OXBYU09Gdwo3Q0dMYVpJZnY4T01CRlV2c3pKMkNjNnQyQlk3QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSQkFvdW9aMG5hWFNpaHZCOVV6dlVaVVNidE96QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0pCS1pKNW1GRwo5YlFZc3BRYk1GdzlIZU5aSHBkLzhUWm5PdlhGNUZhZ0NIOXlVQjUrcU1tTkh5WXhoT3dKNHhvbVlXRlNmelFiCkZDK3R3WnZLMEpGSUxJQlBsRXJOaitnOWdsWlVPVWsyTTYyYXh5T2xReHNKS2UwdkwySXhhMWV5OWZBNHhUS2gKRS9CVTN0WitYeWNudWpNeTQvV0JxdHlZRzRTeGdGaDdxVmh2dExDc2FpNDdIbW5rR0lpYXN5QmI5YUI1b3dkSgplOVBWcE1IRkhFK3RCcnFrV2llVytHWXh0eGRUbXhDR29nSjNNSmtmUzFwR2hUWnlMUmVEaDQ2ZmpydkNMQk4yCmdrRWRUK3o4QjZJOURDME9BeDJVQ1BUeFJKL2ZsYVEyNDhxWUlZVEJXbU1vTTRYR2FTK0JyaFdFV3V4bHpPbUcKaUg2MExYL1hlTURtCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://10.0.0.19:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJRHE3SzdpVmZEaU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1EVXhORE00TURkYUZ3MHlOakV4TURVeE5EUXpNRGRhTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDbHhiUzIKRXhneGM5RHlwbXJpZHNJQi9xam5Nb2oxMVV4eFdhM3ROMC84VnJTcTYvbXpYM2FkYmd3M1ZKRk5FQ0tKSHdiVgpVK3RuRzFtZ1B3b2JscmhFSm84VUptMTcvU2p4NWtBT1A3Q2FuekZxSmJEaEtpa0k5dTdjQTluWkJvQWJnRHp2Ck80UkxwNjNQQVZQY2Vvbkg2SVpiUEk2YUkrYUk1L28xTkNvVmc0MExyY0JpNGtmdkw3T3NkUVk2blJDTmxDd28Kbnl1b3gwbmlQanNxdGRRaUFZVVYzaFpReThaOURNQ3d6YnM1VkxJbktaWlRNcmwvclpaY1NJOEFHaXYyazVZYgovclR2cWpEcVVIRjE3Vmg1cmYrQ1l4L2JJbGNhSE8rZUswMlgzbTc0M05qUU0yV0h0K3F1RkFLU241R3o5MGVWCml3bHVlaUo2UlRsVGR0RmJBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkVFQ2k2aG5TZHBkS0tHOApIMVRPOVJsUkp1MDdNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFZZEs4UXZ6azBlTnhWTjhPRDN3VndlNWtlCmtlcG5tT2NzelFrTEZiME1GcmRLdUNsSkFJRmhzWUZKL2NVYnBZSEdUUDBxdmVYYllOR2tPVG9wT1ROeTFEUEgKL2lkL3EvVHlFTkx0aWtPcVhMVENJZCs1cm90bEpaMUlHWGgrV1UxV3QwVU1ZbUwxODhJVFB1dFlhVjVNN2xWYQpDdmdDVVdGWlBCOTRGWVNmSXhHYWVuLzNuK3dlRXVCZ2lmZTJxcDBZVDE1Z2trdjVzWFB3UlZRa3VXeVQxSTlECnFlL2ZOVGZsZGRXQmUzV2NFM1BNVm41THQ4eHVnd1NRSjhlS1MwZURUbTZpK1g3R1I4QjN5azJtQUtmcXZSOHkKQ3EvQVlVemhhdGZ6K2JNWWNFWW5FV1JHYi92azhsazV3YlI0cEV4aGliTDBjSzRGZVY3QWdJU3FxUDFjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcGNXMHRoTVlNWFBROHFacTRuYkNBZjZvNXpLSTlkVk1jVm10N1RkUC9GYTBxdXY1CnMxOTJuVzRNTjFTUlRSQWlpUjhHMVZQclp4dFpvRDhLRzVhNFJDYVBGQ1p0ZS8wbzhlWkFEait3bXA4eGFpV3cKNFNvcENQYnUzQVBaMlFhQUc0QTg3enVFUzZldHp3RlQzSHFKeCtpR1d6eU9taVBtaU9mNk5UUXFGWU9OQzYzQQpZdUpIN3krenJIVUdPcDBRalpRc0tKOHJxTWRKNGo0N0tyWFVJZ0dGRmQ0V1VNdkdmUXpBc00yN09WU3lKeW1XClV6SzVmNjJXWEVpUEFCb3I5cE9XRy82MDc2b3c2bEJ4ZGUxWWVhMy9nbU1mMnlKWEdoenZuaXRObDk1dStOelkKMERObGg3ZnFyaFFDa3ArUnMvZEhsWXNKYm5vaWVrVTVVM2JSV3dJREFRQUJBb0lCQUR0czc5YXphcUZUc014RApqeDVtenk2UzRXNmI1WkFtNmhQYVA2akJndGxsSmJmK0J0SGYvMi81SXNUMCttK0RRTFlpR3J0L3JXd1ZXR0JECktQYng1VlY4OHg2WWxmZjBMV2ptRHdGc29IMFZZMHYzZmZ5QnRoc2lGa2RsMUFMaU95dGdvYmRyQVFaejhqRTYKZXhzWERHeE85VmNna3NnNzVXa2ZxOGpGemU1TzJmRkNaNTc5a0JQelhqYTNXRHdxRGVVSWJKWTFWaDZMZmJObApFMEJLOXhjWUp5dkZISXpUNnFpOFFkMkwxRXZ3TjE5ZktGN2pMU2dhWUhJVFBaMzdWNFpsV0VxYlhLa3R4L0FGCjZpUzdpRGhoSWUzN1UvUmFsVW9tRnBsemoyYzhycGJaZllqTTE2Z2VObWhxcUZNOENnMVMrNkhMZFdmdGtsV3UKRDZIekNhRUNnWUVBMkdQRFVESE81SkVlaE4xYmtFOElCV0xzWlFGZWVTeW1aM3NGQzQ5MEwwWlRucGJ5RVBYVwpRNTNqcVhNZm0rK3FXOTB5YjBmT0xwbXdXNUtyWUp0eUFoN204MEx1OEtzR01XM1VMbkV3cmliUUZkSjliZnFOClNqQ1dLRWdhS3p3dWxTRWQyUk9yeTg4TDB6MDFtZ2wxand3dHpIcGdPZjNzZk14SjZlb3ZqbUVDZ1lFQXhCMzEKN0xLZnI5MzZVZWFSOWlnNnpYSjR1djNDV2tjblBXbkNZTjhmck0wV0IvaVltbzE1NW1UNlBWZllwMHFJRWJpTwpGYVhGTHk4Uks0RnIrYk02UFBnTFVnTUREdXVtQWRUSVMvSmFPY1g2LzM3V2VuZEcyc3BtemlRRnZPaERiOUxhClJrWEtXb3h3VkNacXRmSlhBVUJSVkdTUGZNL09jN2lsS2RtMm9Uc0NnWUJGVFNZWFAreHYzVjQxMVNMbkE3aWcKNlA2bWxwcW9Ham1zK0lRMElKeG9LNURLUUxPRDVRZmJIZXowcnU4WHBOa2RsS2o3WkxiT3k5L2taQVBJNjkvRwplQmtsSFhHaTJGTWliM2M5N0hoWHZneDBnTFkxQzhKR1dXc3R1WEhRR1BVZVE3M29jTmxiYTVMdzh6Q0FoYmtGCnVEUE93ZjZoZEFaU0xhY2FhQ3NVNFFLQmdRQ0NFNDBscldRVTlab3Q4RXduaEk5YjdPeit1WWpLOEI2cXNSYm4Kd1pYMHV5STlyemtvYVdYTTFuVFRjd3lVQ084dk1jV3J2Z09IUkNTVFFvZ25XaVRxZzJxZXZyaXNrTWZPdHg4UwpvSEFQbWF6ZEFYZW9TcXlJT1c3dWt4M3JLZkp3bk4yQmRwQzhkaUdhN3RBZ1ZkZzNVRDJoU0FHVHV4RW4xL1JVClNiN0VPUUtCZ1FDTW52cE9lMUh5UzZ3bXk3WUc1QXR6TWI2RFhQMHVCYUVYMzdVMUs2WTZCUW1mRzdUN29OeFMKYVRYODVHVEtCUjM4WWlRTmsvMEIrQ3o2dlJRL0hlTUI1UUc2THRuOVN0MHZEV25HWDdhSmpsWXhnOXhlR1dwdgo4bCtLaE5KUDJSQWo1cHowdDRQemFDN1VBOVhKK3U1MlNPWmxpRHcwVWl0YmlkK0o3YkVtUEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbokube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: turbokube
  template:
    metadata:
      labels:
        app: turbokube
    spec:
      containers:
      - name: turbokube
        image: pantopic/turbokube
        imagePullPolicy: Always
        args:
        - /turbokube
        - --provider-config
        - /etc/turbokube/config.json
        - --provider
        - mock
        - --startup-timeout
        - 10s
        volumeMounts:
        - name: turbokube
          mountPath: /etc/turbokube
        env:
        - name: KUBELET_PORT
          value: "10250"
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APISERVER_KEY_LOCATION
          value: /etc/turbokube/apiserver.key
        - name: APISERVER_CERT_LOCATION
          value: /etc/turbokube/apiserver.crt
        - name: KUBECONFIG
          value: /etc/turbokube/kubelet.conf
      volumes:
      - name: turbokube
        configMap:
          name: turbokube
