apiVersion: v1
kind: ConfigMap
metadata:
  name: turbokube
data:
  config.json: |
    {
      "cpu": "2",
      "memory": "64Gi",
      "pods": "1024"
    }
  apiserver.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDjDCCAnSgAwIBAgIIYzW1pwjQ0yMwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yNTExMDYxNTUzMjNaFw0yNjExMDYxNTU4MjNaMBkx
    FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEAwbdr9bH03K6lvivqnL70X/i1H/Abh7oid9VCQGAJe262fjwu+Zw2
    KpFDIqsN0kI0Epn8dATfpNzYBGusEuWMF6qDM02rlnXhApkXdYHCl7Jw7+KffHDU
    nIG3gWddkALpFfCDr6ducEmrdJVyuy/G3btZVOITXdwm8CUoH8Iiuumm8nSWJCS8
    RvQQGDJIEQAm5lRPreL6uFIcj6zKSMRh9Cc4JENbcITJ23gemDXp3XKeXN4eICsb
    tkub8xXYh9mhR14sBRCUOc/eJvph9KbmEim1fOl8/1UxInRNqm9OitYbtDZMOMEz
    FFkli/L7OjmQdjNvWJviTc0vx3WMvj9QoQIDAQABo4HbMIHYMA4GA1UdDwEB/wQE
    AwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
    MBaAFLQgcGNYkyXFOD5K9pPKwV40M0A8MIGBBgNVHREEejB4ggZrdWJlLTCCCmt1
    YmVybmV0ZXOCEmt1YmVybmV0ZXMuZGVmYXVsdIIWa3ViZXJuZXRlcy5kZWZhdWx0
    LnN2Y4Ika3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FshwQKYAAB
    hwQKAAAahwQKAAAUMA0GCSqGSIb3DQEBCwUAA4IBAQCeDeza4126d45ybm2Z85PP
    YrIusDIoQ0ZhzVztrd1iNduQ4PyBU8NcPt3M+lkV7PQCG2raeDlIf4D9QcnuCfl9
    cZ7swRIyEX/xg87EasMQF32Ho10TD6sdBZecw0Cs2BRaETEPjAiuAV5qHmKsfNkP
    bDTospmY98wptviuetgeuS4hOlzm15y0D2jrbbUBbUkpCAoo5imtEWpk0os/GTkV
    GH2VZ9VEPG4QvxykvuPmNJyOTSnxOlfS7sMKkNU41FfkgJsoxoEp+xDAIKrAkbEA
    xtZs5GD/aJo4TDiSRXv+0KVQDni/NMJzdSROoCxhpOqRDFM4VoCRudM/McFqlehF
    -----END CERTIFICATE-----
  apiserver.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAwbdr9bH03K6lvivqnL70X/i1H/Abh7oid9VCQGAJe262fjwu
    +Zw2KpFDIqsN0kI0Epn8dATfpNzYBGusEuWMF6qDM02rlnXhApkXdYHCl7Jw7+Kf
    fHDUnIG3gWddkALpFfCDr6ducEmrdJVyuy/G3btZVOITXdwm8CUoH8Iiuumm8nSW
    JCS8RvQQGDJIEQAm5lRPreL6uFIcj6zKSMRh9Cc4JENbcITJ23gemDXp3XKeXN4e
    ICsbtkub8xXYh9mhR14sBRCUOc/eJvph9KbmEim1fOl8/1UxInRNqm9OitYbtDZM
    OMEzFFkli/L7OjmQdjNvWJviTc0vx3WMvj9QoQIDAQABAoIBAAFZzxXqhMOZMCyw
    T7WCG2Aj8tdjLD35DU56nTinssk6j2k38DfrX/FSC/7M5I7HyWcrzbfdZNXYeGUn
    fw6urRhpJvsPmpe1ALms6Z33Jq06IFF76hLLEqB4wxfS6bMcYhW2FKT/7OQ5j0mD
    1UX64k8fhFL0NKBd7aOVDr+R8f4NqfHOog57OL2+hetdMlxiVhoSpql3HDyVngX4
    RHVbJdMalsA4oCUFlsuu5mzc1ugVA0hXa8WfUX347vNbS+LfMc2lNs4Ib+y430dx
    j/oxzI4zb6BJLGdnPRwWUIPEyhWOhetQBgk0eUK2+kDlHGmWjJQRHnqfPZ0J3gjw
    rccX2mUCgYEA1xoG9RBcvhBL79p1xRGYaPvOOlrxMRqEQKRg/u4rDcM7hiT0i/zZ
    9gZp8QMLCaXPyZCTbDXJ0Ov3GXZbX+aDIahSfSf8yLTOu78BCl0c4lrFvBqn9hqJ
    wwMpQMxl60MEI2VDAvy95L219vDAxJedH3q7YHXLJ7T1Ib3DC8m3Lx8CgYEA5ox7
    JlW53S6qjhlCjDH9mLcgR6yzNwWEsiMmlTpUU31u246AdgV2RfSYewUN4ELifKbt
    FQrR0sACNQVF0ZqSDx2irZrXUd9OcBf1L2U/proyNyirkuT+rcy1tN+L/bHpyndQ
    o9rRMIspFOjbNs3EHtoHKD0pGspuI/4YDa/WSD8CgYEAwVuEJYcv1yqPGG0osJ3A
    g57XI13csmdDu1gIWSF/Uj/NoihWLAB/bckWMrCpm2KSBn8QBpXTdRqoZRsfyHVO
    K1ND032+nizqKZrpNIe/DzrJxO2xTmlMrSCKVNVoSLNVZPwB4Q2RJa3jhLemkRI5
    C7Mn/O3mUSs5r7sFOfN518ECgYEAjkvyzqxmtY/SETaiDmnkfle5AsQjMTikuFZd
    wAlqdsWaoMUJoM6qO29Gldd+wwZFSG63Mh+ldhCwzAzfFQn0UIQYHlLNx2iuvxzq
    ZkB10vBlggoGK/pO/vK0zFiVzRX8mMyf5yJtryqVRqSaeO7zt58Wf82QC0saQ/jW
    28vF1H0CgYAYI+Dt9uYzOgzeyZV1ZItIk8SBcSZNpy/17Qmcq+Sva+HcYZ+F2jH4
    6SeAcsqNgE+8ED2aW4oy8akGlv8xOCSsFV8NQTGLPN1ACdGxW/wF1JnPvxBu3Xd8
    zEoNCoz0OGsnIlrLnsYnhl1ltTOYETlwLi4XKAHYO7KWTO8mix/CPQ==
    -----END RSA PRIVATE KEY-----
  kubelet.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSDJwaHo1cGxzVnN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1EWXhOVFV6TWpOYUZ3MHpOVEV4TURReE5UVTRNak5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURNNmg1TEUwSmxUeUlUeXVRRTR2LzQ3OURySzM0alJUVld4N2xLU2lWWGR1VXdoS0JZdlIxVGpmOG0KUmNIMnVERWRkMWJtZFV6ZjZWTitCVWhPckdCYXlEUGRsWWM5anp4VDNFLzRMRzZTeENCYXNFR2p4S2hIWDR2LwowVk81S3lKbXdCNS9OZ1A2VFdMNThRMERMV2JSb3JsTTc4RjlUZlViLzV2cDNFU25Ub3pWZCtDN3dkY1BBWm43CmEwMjhIMitJT2RBUG1CSG5tWmgxcld5NDBiR0l6aXpFMjExR0phcHVKMWlEUWZtUDZTaXFxcG4zY2FQODFMbDkKbkVCeDU0bWF6N3VkNE5aQ2JPQmwxNkNkdVVwSnRMcEw5bm5idzdQSUIwQ29HU0V4ZXF0MUY2TmhZMDJiWktlZApSRTFRYzh4ZFV6M2pWVTd6czk3aVZkVll5bDlEQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTMElIQmpXSk1seFRnK1N2YVR5c0ZlTkROQVBEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ09oelN1MTFuUApJeHVPS1J5OWh6L1lnbElFK1VLUUNtTWNwY1NzUXFqVk50NnJGVXJOOEJRZVh5M29uN3BrWlpNMUYraEo3bkp3CnU3Y0NYbVJjWGw1WDRTQjVsWjVDaUlhU1d1Q2RmY2F4dVFVN3hsTTd6VW1rWGxrMGJMQUZkK1psMFR5TFo1RGYKWWdFOUxJcjBxTHczcXJ1RW5WRTg3WXpLN2U4d0w0cEliWThOVFNMeFJ4eUpSbGxXVm9UQ0VFaXZzTTdZTjZvSgpQT2NzUWNTb2xoSitGZzBjcmZlQVJCYkU3bHFqMjJPYkpnY1VyM0RsbUxuOWpaUmNTdFJiaTVDR2Nra1FOY1dCCnRoeTZpM1RZeXJNb215bVVVQmxwaldZYkFmTUpqaXFiMk42elphQmROSExUY3FQdHQ1endyTVlMOXBBUDZVVEsKVTRDd2IzR1NxNUg0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://10.0.0.20:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJQTJrakdqak9maWN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1EWXhOVFV6TWpOYUZ3MHlOakV4TURZeE5UVTRNak5hTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEUDVRcUwKZjA2M2xIRDhldTYvazdnY0tucGZaRGE2L2EwbXNacTVNcHR4clZJNyswN2Fqb0dJbjFkT3RXRVpPbFBWbStlaAp2azk5elFzUzZqVEJ5cDZGUzN6UzBTYVFWbm9OYktDaXNmVGdWUjhrcUd4RXBIMEdrdE5IOXVqZWdBLzh3b3BuCmQ1STB4VnY5RXl2ZFlxbEgvOEZFVXBFNFlSYUpZOXBRczNnZmsvZlR4cEl2TDRIeHZZNFB6a2RuWnYrMkNUbWUKcUQ4VVVVSGNuOVF5VGxiendZMUh0L3BBclRXTXZPTzlpVXRXM2M0NDkzTm5jaUJ4bDduMnNNOXRGT2ZrcHE4VwowTE9hWjhBaXZHcHFqRmg5eVNKK29ickhxZ3NxNFJES1UzTkkzNDd1QXFrV3RsMXoxK3VDbmtqUGlaSFlyRlM2CnIzNlMzNlFFKzFldkNQV3pBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkxRZ2NHTllreVhGT0Q1Swo5cFBLd1Y0ME0wQThNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFJSGZVYlFvcXNCTWxtN1NIcitsTkFybmQ4CnQ5MHFRSlQwcnBhaDJSaEY5eUdrUjdQZndjbXdkVmpHZWNkSjI3QXk4KytkM3pNS0RLbXJQakZ5ZlowQVNod3cKbTNSMmJnRHJsN1VKdFkzWFQrY3FPYUN0WmtPTmJMZGJmNzdsbyswZ25Nb0N6ZEdOY29qbmxnZ2Q4ZUhRUmQ3UQppUDdVMGpqUDF6YmpiNitpOWVkcDFjWWhKMS9aSDdsWlc4c3l1RjIxR2U1OHVNYmp6bXVlTXBTcWRtTTJaTDNiCmFJVUJlZXQzZitaeFMrbk1EUHRZcjR2aUV1SXBYb0ZCVGVjL1RrNUY0SVRCUjV6SWpRNjhUSFlZbmRJb1ZYOG8KV1hyUmtNNUdCYy85bVIrSVBRR3FQTGlISTRWMkhncDF0M0Qyd0U4b29SeXJEQnE3QUFJS3ljV0ZvU3BaCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeitVS2kzOU90NVJ3L0hydXY1TzRIQ3A2WDJRMnV2MnRKckdhdVRLYmNhMVNPL3RPCjJvNkJpSjlYVHJWaEdUcFQxWnZub2I1UGZjMExFdW8wd2NxZWhVdDgwdEVta0ZaNkRXeWdvckgwNEZVZkpLaHMKUktSOUJwTFRSL2JvM29BUC9NS0taM2VTTk1WYi9STXIzV0twUi8vQlJGS1JPR0VXaVdQYVVMTjRINVAzMDhhUwpMeStCOGIyT0Q4NUhaMmIvdGdrNW5xZy9GRkZCM0ovVU1rNVc4OEdOUjdmNlFLMDFqTHpqdllsTFZ0M09PUGR6ClozSWdjWmU1OXJEUGJSVG41S2F2RnRDem1tZkFJcnhxYW94WWZja2lmcUc2eDZvTEt1RVF5bE56U04rTzdnS3AKRnJaZGM5ZnJncDVJejRtUjJLeFV1cTkra3Qra0JQdFhyd2oxc3dJREFRQUJBb0lCQURhcUdwNDRrT203cWdQeApqVEtwdEhrUGdGTHg1bVEvek5aR1VCRlBhY2szMGs0OFUrMHJHSXRrbm8vdktJTjZMMDRWS3hDQUdxWFJFdzdiCnI1aWZYeFJjbDR0VmZJYnFmamhtYmt5cGIyTEhieU56OTlnS3ltYytseml1aDJmdUU0WWFYMHM2aVNMQUhHS00KdG5XRmVrNll4T2hpcjVXOERiRjlwSXVnelQ2Nzc1eVJsQW5OK3h5SURDS3dieElhaTVBbEdHc0Qwenl1dkxQQwpGaXFxTWhLNlNVamVLeHUwZ2JDcHpYcGFCVjlkayt6SmdTYzBhSXlaREVBTUVCc050OWk1UTljcDc5MVV0aXV2CkZTTlJpUjBEdUMrYWQxZHZSMm5EbGJIRk1NaTh2YThCajE1N1p6S3NRbEZndTFpNHlpTFg1RzdCSVg4YXJhK3gKaFZCeEF3MENnWUVBOVJhZjcxOHJwK2t5TWplOE82UHhrNnRDdXVJREc1YXB3SUsxVUJmR0EyMnZnRVRqS1ptTApPb2Ira0R5UStYRXlzVUdxUGdoNnVrWkNveVlxcnBpR1lQTHR1U3FocVFiVVoyQytMS3I0SDQ3K0hBVHNKMTY4ClowY2daZGtJdGs1TmJ1WDdVMUZBS00rVGNnSkxlcWErL0ZyQ3BJSVNkWUFzRUE1dmZ5Ky9lVGNDZ1lFQTJTYUIKSHNNdDhrajRrVTVWMWZwaXZ2cDJKYmhlMW9Ram9pVW96S21PcmxLVk9kMkxXTWJ0OXcydkZRcDVVck4yNS9Tawp1ejg1OU1EekduOVJmQ2RYckpNUGhnZm9YMkEvaC9hU0tWeEdHUGhaQlNJMURZL2JFTUkzVEZROVhnZXNVUnAwCkZuTFEwb3FQZDFEQlF0dk14dnRCeVNPcWY1U2NqZ21lSzRhb2RXVUNnWUVBNHBwaWtYMmE3WXJNNEdWcjRuQzQKUVdKTk5tRVZvb0p3dlErYytFcWl5RFMzMlk3WHdYUzNxQXQ4Zm51aFJ5Q0VVQ040ZGhaODhwRlh0MlRvZmJtRQpOVXNteE5kSDFQSDluUDl6bGZVVnFJZ2JKbWpldDUvOTdqZHpHdmZKK0ZUNWZ4bWdmKzVWdGVZR1c1a0hsSVZyCmZBT21oMWZFSFdPK1diSWZJS2RURDQwQ2dZRUF5NzIyMUZnbzJmVGhVK1I5NE9DbW1hMkNBTzQxL1d2Snl5NjIKVXlDYndLKzNWNjJvT3NtYktIdnNVLytaeWFDYzVoSENKZld5dVJQNGhGb0U2RW81bHEvOGxyTUFzY3dxajdVbgplaXNia2Y0aCtCRWFXZmtwZjFYYWNJRnhlcklVV1p4S1kyMml4SWhCQjUvN1ZISEtkci96LzNhNVdDN2xuTmNsClVvMXJyWWtDZ1lCdG14VUx0N2h1RlFoZGRwRU9LSzJsZndNSGNuWFhsZzBtY3Bia2RPR203VWNnRWp1N0lzV2cKdlJGLzFZWW9ZQ2FpV25sY0VEZUtBTjBWVjNldlZNWnd0S1VkaWhZcU5nQ1NRRTRDeFlXRzNSdk5QVGdTdDBKcQo5czRkV2NJS1BuRFREVlJ6WFNiZ0Q1cTdvVFpwamIvbE5hMjZwTXFQU3hwWGRzOWcrSGZxNUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbokube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: turbokube
  template:
    metadata:
      labels:
        app: turbokube
    spec:
      containers:
      - name: turbokube
        image: pantopic/turbokube
        imagePullPolicy: Always
        args:
        - /turbokube
        - --provider-config
        - /etc/turbokube/config.json
        - --provider
        - mock
        - --startup-timeout
        - 10s
        volumeMounts:
        - name: turbokube
          mountPath: /etc/turbokube
        env:
        - name: KUBELET_PORT
          value: "10250"
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APISERVER_KEY_LOCATION
          value: /etc/turbokube/apiserver.key
        - name: APISERVER_CERT_LOCATION
          value: /etc/turbokube/apiserver.crt
        - name: KUBECONFIG
          value: /etc/turbokube/kubelet.conf
      volumes:
      - name: turbokube
        configMap:
          name: turbokube
