apiVersion: v1
kind: ConfigMap
metadata:
  name: turbokube
data:
  config.json: |
    {
      "cpu": "2",
      "memory": "64Gi",
      "pods": "1024"
    }
  apiserver.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDjDCCAnSgAwIBAgIIX2u6ZbWXW14wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yNTExMDgyMDIzNTlaFw0yNjExMDgyMDI4NTlaMBkx
    FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEAr8e3Qc62nqsDZHg0wbqTvYyEoeQDllcJYhplQAyHq3sWhzNWg22X
    WbhxE9W6IYh7n/Ku0lDn4WiLWaFlHIVmmoERajXuc4fAH+zvQoB4+izJw3Ct+nft
    9TSecOI9AygxfdPISyDws4CC+V7BaEVbkib47mQaMnylPH6f6m5S2jlt2qjT16GE
    w3Lf6BPKEmLXlSbjbPW7sd6NR79IsyJsuCJnTwJklozMlHIsv/Do+xgbWX1BDJNQ
    oEY/IGoj2iQZLoDvfrQLPaf2xCt1rUO0hXcLEMSYlegqKnatUtfTtTMjFLMtxRSG
    vQPc4v8sWCRtIpdQgbUctLfrYwWIeE9vSwIDAQABo4HbMIHYMA4GA1UdDwEB/wQE
    AwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
    MBaAFKbORLUgOdRGmozoPFOctGX+Qi/5MIGBBgNVHREEejB4ggZrdWJlLTCCCmt1
    YmVybmV0ZXOCEmt1YmVybmV0ZXMuZGVmYXVsdIIWa3ViZXJuZXRlcy5kZWZhdWx0
    LnN2Y4Ika3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FshwQKYAAB
    hwQKAAAghwQKAAAcMA0GCSqGSIb3DQEBCwUAA4IBAQCDpfz7akSy3gb5nbuVltq2
    +08VvKQrHi8bwjwDNxF1hi1+ehSKsJ7xkQGD5/CHQnXTVf5pJi6ABt/bOPRET76N
    m+z6KmhqY5Y+S8mq7P7zWFMysnG9SrWyQuYsTbNkF4Etiixvz/pVA74oschaKjsy
    M/9PQ6htEh09gl8ZOS3c5bR4O6nNSWxXXsFwSzsq0f5j2t2SFZPQgtE1lgV00+fb
    euAJml+j4ln9qu3lKqjpTHSJXdOEL7AN75nX8uH1XyIsJM0JLuZILggzYOc00MOi
    LnhuL5hXtwT6MIA1DzB1KwPxiLBLQNiRgKfEY3u7Zj6W7bzz8h2X8TYZQvD0UDLz
    -----END CERTIFICATE-----
  apiserver.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAr8e3Qc62nqsDZHg0wbqTvYyEoeQDllcJYhplQAyHq3sWhzNW
    g22XWbhxE9W6IYh7n/Ku0lDn4WiLWaFlHIVmmoERajXuc4fAH+zvQoB4+izJw3Ct
    +nft9TSecOI9AygxfdPISyDws4CC+V7BaEVbkib47mQaMnylPH6f6m5S2jlt2qjT
    16GEw3Lf6BPKEmLXlSbjbPW7sd6NR79IsyJsuCJnTwJklozMlHIsv/Do+xgbWX1B
    DJNQoEY/IGoj2iQZLoDvfrQLPaf2xCt1rUO0hXcLEMSYlegqKnatUtfTtTMjFLMt
    xRSGvQPc4v8sWCRtIpdQgbUctLfrYwWIeE9vSwIDAQABAoIBADKEAKRG1bCPkPAE
    o5SxG9gzU8J6lpVT+fxZfZOEhlC/lN/R3yDyE7bTDJwYpd8RLAXxZlBGs/zRYIqn
    mTkzFSN9yBVv3lERSCNkofXImfu7d1hVP4plgNsg/g+O1N3dZSu1+y+sDcBoRDuK
    AacHl6NO0+cemXC85XeXJDno7qKLuHnjxHt7CQnziIj5KtbC791u0A725isWrYRC
    b01vSncv4cUGLew7UG7tWZI37oWegPXkSJOIAJzF52CCZRERgJ7K6U+xFHge+gQS
    hbytDO5k8pI6PhuvqBYvfr8emiXh41jvNDNNvrg9Hn3qTUG7e79NgfDNFeMZWsZx
    6Q4Iw8ECgYEA3ibQFJBaXCwOyW/eXJWV0gDGUneO4czPxz6X1s/ezjkZE7vVb/9Q
    dKld7NtM5Kt3wyK0MQrbxI1k7+TeVAhin19UJ4Vt4/J/H2nD3ZhJCJKv4jMTWoP8
    iO9vVeFfp/+Ta6G+Qfr9UBslhzjd1xWh1pDbmet3Y8BgLRUxDgy7UDsCgYEAypAm
    TPL0/7EglMN82ExAcLXOLr4fNB8c9LMPa116snGFVLRQjgRB6ERGj+B8+CNo6CAY
    p0sG1++rLq/KsjjqJgx0vPSltMZJkeig7fhJ1uF9csQEzeEEnaTyV5kWLeCvKwcp
    Q4IUJCWU2A5ufrdeKuEYlkl792w9BbivNuvB/DECgYBQsuq9vZ6Fgx+v/ypYmaI+
    Ejf49yN5VQxZhZxk1UhLw6Qfbglf0PBqIKhVBWkOXFd6FF4+voINCYwUNSCqiA1D
    db69SJQdzRZu093p3osRSTAJTKKILBANsmTQXrl/7rCf1bamg0WH1wSv9XFo05vh
    tOeBJ29MVjLZzavvPaLBxwKBgBsHeyTfcpO/5fIT18/g9ORVTirskatZz3pTfmY8
    Nggjn7/6w5j/tm+w1J2UPfi6eOAokEGagFJGF9iF+o0njQ8AsH8aQhZKMzz2Bqta
    azfyJNQwldeHBB+pB/Fqaww6JAWg0f/BFsDwBtmBq3rbKwSbvrUnHxSX69icmTzB
    3sOxAoGARdMv/fKio+yP+mIwOMrKg/R+HVqrwoZ/ZC3ERK76fUYTl9qs08sutoML
    vTJq2yzK/W9RYhTL+WXKTUkVIxc1m6YUutER9jNpgkyWNvDBnVda8C/MlTGSaNGg
    D5z68d4+zjhex/MCJ2Pm4qP0Ru7Aqmok6ZTh6n1BlezuPKLPoRg=
    -----END RSA PRIVATE KEY-----
  kubelet.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUEdGR2FKQkpVcWN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1EZ3lNREl6TlRsYUZ3MHpOVEV4TURZeU1ESTROVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMwS0dJdDcrZHlvSTc5b0pNOGVRWFdCZkxrWm9kZi8yYlU2clJUeUdaRFVjVmM1WkZpUkRBOTlXMHUKaUNhZ0FNTXFtQU9lTFpwcUVySG9YREQrTjYwQi9pRkZmU0Jpb0JnbTFwTkxINWgzSnNqcGVjc2RiYjZ1UElmRQpKZi9LdWp5RFMvanlWQlFNTWxVY09aajRFWFU0Wk4yNTQzQWhtMXByZEMxdjd3UHJFemE1dXVvZE1vZFNMWHN4Cm0rZW5XN3dCM2pMbHF1V0xwYXNxem1MWk5YbEtiaE5jamdnQU80L3kyUXVHNlp5NzVtc29SREZjTUtOZHEvTFQKTGtlUFhIT0phdkFjL2JOZkcvTXJBTm9GazdYZC9qUlEzaVhZdzNtMmVuSVRoTExqV1k1ZXBiRllWVHk3bUJDVQpsdE13ZkoxMTJjSk1VOEZvanNSU2RXNXA3TTQvQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTbXprUzFJRG5VUnBxTTZEeFRuTFJsL2tJditUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnRwYTM0RTJUMwpDbmlUbFh0TEZOc0R6N0JYbU44T3pYUFJhenFocjF4YUZxem5ubFFTbWtTcFN1YjdkUm5rTTRrd29FcHNld0pYClRwNSs5MFUzYmRlUWZFMVB6enhCZCtab3VWc1JlSXFFeHF3THYyQ2VSMU04MzE5TUw5ajcxaVFWNjJHMEljQkcKZjdyT3ZDL0N0RHRlMUdDcEFoZUU1TUxFcXlPQTFBY2pHSkZ1Ly9WZUwrTEUwdnVUTUlMeUgyUDUrU3E4REE2UApNaVFvekw5TFFQWnBXVEtMa0Vqc2ViVDg0cHZ6UEEwYm1kcEZjWExnQTZzRUVEdmUyaTJNc2NyVlZBaHYzWHNpCmdUZkNFTm1hZHhsM2lFVXJtSUoyaU1lUlIrSEVVUy9zNG5aZlg5aytuakdwU1ZpZDBVZ3J6LzROMTg5aDZQNlgKVitPdkFwZXh1bE1iCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://10.0.0.28:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJYW1veVovTU1IaVV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1EZ3lNREl6TlRsYUZ3MHlOakV4TURneU1ESTROVGxhTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEVGYrVEkKZkVBQzlmV2V4RU5pS0hXU1NIOEk5NzE0TlViR1NsbURzekxLMXhaZ2NHZmhmaHN2QUxzWGV4WklzMXdNcEYwUwo5ak5qNmd2MmtiblluLzEyQnFkdHh0ZlRVWWFzdFB1dGd5MWRydmZFVExXcGNsbnhTSXlZODNTSHhwOVExRUVCCnZIcndzam5HVE84RUhGd3RHOHJncFhVelZGT0NBNWRLdTZyRllzVDdjamNUTkd1STl4REhwNkh6UlFJdFFuVksKQ25JSlVZbkszWVpEdDhFcUo1bnFMWEdhZVkweWZad1ZmakJSY0l6WUhQL3NHSWZZWVpNRlVEQjcxSFlkL1ZlaQpxVEdxYThZS3lIM3RZTElSUitBakVlbnVWWmZxOVc3dzV2T25aOUZTekdINzJQWnZRWFFnUWtmVVJVOXN5b3BhCmYzV1NWMDNwWVBBNHZxUlJBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRktiT1JMVWdPZFJHbW96bwpQRk9jdEdYK1FpLzVNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJFOHpqUndXWnlqbFh4SnlaTExFL3RZQnlVCk5OR0EzRlg2WVVYcW9yZ20xK2xNc3IzMVVqYk50WUx3VkJvckZOeFhVemJsamhtSFZZRG9QblloTXRzcTV1RnMKVDcyMjZHN290L1NFSXVId0RsZ1YyenN1YldoM2NESlpmSmR4VmVscTdDTFpPa0ljeVJySm5QTVdqdERZUTZZagpvejFPREdOdFBZQVIzWERxRU1FN3NhVXNFak0zMTl1Umsra3Q1ajFscFp3TlduNVdOQmpTeHdMYUliQU1QcDZuCnYzU0M2UGdETkVhZytNL3M2K3puSXRxWDZLN3ZobzZWVnNNWm4rcmhES25Fb2FIeU9XdVBGQWNVZDV2a3Q5TEYKOG1seStqSjFOdHhhMVZRNWtGdHdEd2JPMi9RcC81QTR5N2F6bmJKWk9qYjJPOWVQemhadjJZTUdjU212Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMDMva3lIeEFBdlgxbnNSRFlpaDFra2gvQ1BlOWVEVkd4a3BaZzdNeXl0Y1dZSEJuCjRYNGJMd0M3RjNzV1NMTmNES1JkRXZZelkrb0w5cEc1MkovOWRnYW5iY2JYMDFHR3JMVDdyWU10WGE3M3hFeTEKcVhKWjhVaU1tUE4waDhhZlVOUkJBYng2OExJNXhrenZCQnhjTFJ2SzRLVjFNMVJUZ2dPWFNydXF4V0xFKzNJMwpFelJyaVBjUXg2ZWg4MFVDTFVKMVNncHlDVkdKeXQyR1E3ZkJLaWVaNmkxeG1ubU5NbjJjRlg0d1VYQ00yQnovCjdCaUgyR0dUQlZBd2U5UjJIZjFYb3FreHFtdkdDc2g5N1dDeUVVZmdJeEhwN2xXWDZ2VnU4T2J6cDJmUlVzeGgKKzlqMmIwRjBJRUpIMUVWUGJNcUtXbjkxa2xkTjZXRHdPTDZrVVFJREFRQUJBb0lCQUFlMGM0MjROUTdHamhXawpHYjVVTWdCTHd0RDlVWG8xR3Foem9mSXh6NHBqTG80QjJrNzFMS0ZZT2ZpZmc4N1BOZTNCK1NBTk53OFBRak5QCjJNRGpCelZMQmNOeWlIOUt5NGkwS1MwSGg5b1BXemhjQVF3MHZjRVQvd2M5YTBQZEFRWE5UYmIxK2xhVmI1UmgKVGgzTXVMRHQvOFNTVW9RMXNMc2VUVjhzR2dzSnZwL1ZNVXRvVlJjN3o4cVNNTjdJMHlyK3doYi9lcnJsZEEvdQptT216WitaUWxITUJRZ2JBV1JLSHkyQXlvRisrNkFUSW9KK0hIUmVVRmtZY2kzd2J5a2dwSnZYV0loYlZmSWhUCjllQW1VVnQ1UTBMbVlxL2FQblRWME5NbzVOdU4ra3BIeDl6UFBnRnljcWFRK0h2NGR0VFgzY25hcmJLWnFpc0gKNHI2a3dnRUNnWUVBM0hVZDJLaTd2RHAzbFZaaWxCc05rdDdyRDZTQkFhcWJiTnpKZTdIZTdyUHRrcDZZczQ5UwozUzduRjVxSmdkMTYzSlpNWmRoK0ZnWVhKb09UK2xHbW1hN2NjRnkxZ0hLQkVqSEJvSUkwdmJnSjJ4Qlc3RzV5Cis2dHduSkNIYWRERHZTWE5ReXFreDB0cWQzaXo3KzlGLzZRMEgrbVYzTC8wVlY3OHIycW9yOEVDZ1lFQTlaa1AKV3hUSThXZGllYUhZT2hQZHpMZnBsdU9jNERnWE5iWVc4L2VFRE1URmNrdjgyc2RsK0NMT0JEMW9oOC9nRGVYYQpoN2wwaHhYRkRUZEphckJKemhJNW14ZE1pVWZVNVlOTkUxZFFkc0c0WkdEOU1VT0dYUldDMGlvbHZnSk1tWWxCCmxhcWxLbWJjU0xxdXhnVmloQ0ZManZzdXppTHRiR0JhaFF6NUdKRUNnWUVBbjI0bkpuOW9QVWkvSUlXM2hzcEYKdDdoMG4veGt1M0xKTWlJOXA3SEx1aTd2R1lDT2lCU1haWk84MWVvUmxaUTVmUHRJeHNLWTlJNTFBWXBZWXNmWAp4djZaTnIwbEdYNDFiNVlDSkhUbGRXcDUzaTNqM3RwRlYxSDFmNVJhQ2FGTFhTZlFXTW1uSHVXZ1drUTFSTWh5Cmc5MFpRUmJwSlJyQXRWaWJQclRReDBFQ2dZRUF3Q2l5NEJQQ0tVYzN3RzFHTGlMUEh0Y2krQUU5QkI0KzRyS0gKQVBtL292SHVmc0EvcGJudjZaYnAxRjFyeFI5N2NjUlBHSFNkWFBoR2hsR2txc29sNVF0VGNTcG9vdHpHRVpHTApJNy9rWUJhd1BERzZ5T25KWGxsdlV4clJEdnJqamhuYmE4dnBrT1NNSkllVUtiR2E1RURjeXBGempLdTlVbGVOClc1N0w0MUVDZ1lCZmxTaXNkRUkxZWlEaFlRSkQzUiswb2dMOVFlNHBPdmdVZlppZ3Z2RndwczU2cjZBSEVKODcKb2hQMnYraG9uOSt1enlDSEltR29rMGlYTmtOOXBVUHp6V25uL2ZvaW1JUndxS2RWbWdGZVoxT0NUYUxlNEVEbAphVndzMFFJZHlwSjcyZDZiSzFpUUY3TllQd0g3RDMxQS9wL2dRb0RuWEwra1Fvc2JLeFI5TVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbokube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: turbokube
  template:
    metadata:
      labels:
        app: turbokube
    spec:
      containers:
      - name: turbokube
        image: pantopic/turbokube
        imagePullPolicy: Always
        args:
        - /turbokube
        - --provider-config
        - /etc/turbokube/config.json
        - --provider
        - mock
        - --startup-timeout
        - 10s
        volumeMounts:
        - name: turbokube
          mountPath: /etc/turbokube
        env:
        - name: KUBELET_PORT
          value: "10250"
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APISERVER_KEY_LOCATION
          value: /etc/turbokube/apiserver.key
        - name: APISERVER_CERT_LOCATION
          value: /etc/turbokube/apiserver.crt
        - name: KUBECONFIG
          value: /etc/turbokube/kubelet.conf
      volumes:
      - name: turbokube
        configMap:
          name: turbokube
