apiVersion: v1
kind: ConfigMap
metadata:
  name: turbokube
data:
  config.json: |
    {
      "cpu": "2",
      "memory": "64Gi",
      "pods": "1024"
    }
  apiserver.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDvTCCAqWgAwIBAgIIE7UKE2b/mYMwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yNTExMTAxODQ4MDJaFw0yNjExMTAxODUzMDJaMBkx
    FzAVBgNVBAMTDmt1YmUtYXBpc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEA2gAd+xC0EJfoU/jWQyn4Wvh8VaUBb1xE3bTi5Nnin+0Dn+wCfOKp
    hL9UGhFP2B7Myb2CFG3fWBfRUDYPecG1LRiFVM9w27GbslysGFFkClMFIE/Amfui
    Wdzwo6OekWK8soK390fn5YJx82GEAV+WLFBEY6iJwlWM82fsiGJ1PBXuMti49n2r
    mF3nErtps9bTvPgXJUgTmyXUpJrz7TiBpiNUKjZhD7hmdszruLZYjgiB1u2wn5hF
    rITF5ZWnkgFzPmAtpYNqZUL5HbQsCGnN7J8zN81oDqYsys3bf9KDX9eRqGQvloMK
    MJf+3DiB42nSXo7WkNc76qUYkk7WytpAwwIDAQABo4IBCzCCAQcwDgYDVR0PAQH/
    BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHwYDVR0j
    BBgwFoAUdr+WT+TeMjDlpixqQwr9pjSyK30wgbAGA1UdEQSBqDCBpYIzYXBpLXNl
    cnZlci00NjRiNmFiNi05MWZhLTQ0NzItYmE5Ni05OTZkMWJiMTBhNGQtMDAxggpr
    dWJlcm5ldGVzghJrdWJlcm5ldGVzLmRlZmF1bHSCFmt1YmVybmV0ZXMuZGVmYXVs
    dC5zdmOCJGt1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbIcECmAA
    AYcEk7bBiIcECgAAIzANBgkqhkiG9w0BAQsFAAOCAQEA2w9yyYqvUp7eDpZArAIp
    XS1f2DkcHA51PbkvziG3ImCvhGZx1xsFwuK5E9QEJwdQyZ+785r25kCtqIBfDs2I
    MepN8TkkpiJRBu6WVFrHknkGX+95dgyjEqGIyGGf8hOX+sIs2dTqiVhe5SrSVQBs
    T/3YX/f9MnsSimxazW38k4CO9jLy17Fhs6IMr28XV7PHtrvsJ2a12mTWTOgqSjL/
    BXknfmc8OGaczegn+jioJgrKTNa1sWqSguo4HG1G9U5I9b95K9DLlPemqMPpDZMS
    rgPldeuB/+rerYUAuhL+jz0NSjfuu1DdC+JQP6hp6IBpd221J7rtc9ScojeK7Y6X
    OA==
    -----END CERTIFICATE-----
  apiserver.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA2gAd+xC0EJfoU/jWQyn4Wvh8VaUBb1xE3bTi5Nnin+0Dn+wC
    fOKphL9UGhFP2B7Myb2CFG3fWBfRUDYPecG1LRiFVM9w27GbslysGFFkClMFIE/A
    mfuiWdzwo6OekWK8soK390fn5YJx82GEAV+WLFBEY6iJwlWM82fsiGJ1PBXuMti4
    9n2rmF3nErtps9bTvPgXJUgTmyXUpJrz7TiBpiNUKjZhD7hmdszruLZYjgiB1u2w
    n5hFrITF5ZWnkgFzPmAtpYNqZUL5HbQsCGnN7J8zN81oDqYsys3bf9KDX9eRqGQv
    loMKMJf+3DiB42nSXo7WkNc76qUYkk7WytpAwwIDAQABAoIBAACp+Do0uZ4RuF8F
    5peOkyqqKXn65kXRwOvwvX6Q8B3CLQnZppBKAgldEJzogv1XhEXBBZpmU0Q2nlth
    YfhIj/Ky0AUk58t9GP1/RsIamifMS1TnD63oYRaak6kL7VNObhPlGtMhk7uhNnoI
    e/+jeOOdqV4PiPJGLG25WhqrbuWSvuL9UdPr4EZ6eSWYhAknleW++XkD/98hoOxB
    5hKwGeYMFs6KjBxsOsoWF3zo9dYMSM0Em5BgYXD404DwqMtouKZ/GKRi7IqHEQjU
    u7X5o2rGcqxIBw7Tc62WG3kybO1eMkGF20NIEMFnLJQtCKH/PJGkIEvIbbPB1HKB
    gHwTUYECgYEA61q3o0AWcsn5kNo9rbCLdN0ljW4ePDF1OaYribWVoEv3frHh3KY8
    NkBLs0rjQC4/ECV6uHGzyJgWp35PDL4lFjwNhxaSoGXlltJhhyisVHNPiimvehtb
    4g1TbdYTes+UqcTqTAfWRFsJgqUgQ3cDIOg0+d90MDuFTv7vGQQyVuMCgYEA7R+w
    MmOsOmdW9zjsgfNdANJkNp4wZh9t161Zcaxh//GHmKM6B4dRFBqygQUa/OqpkuiW
    pdvhIZDAnnJacKvz4uLXFw/A6f7XiGO7oenPLxFXCZg/nE9+fLYO32vMudKKL48y
    FWZ+jZHtaxfItrBJwD2KKsob4eQNkbz+iPaetKECgYEArbC/gd1UM9bXNY26oyp9
    YPusMRopeibN6oO18eVuzWQC/R9uHpcYLLl6pJEJ8V2v8MyYKvLOyaVkYqwWzsKt
    QCGFokKIZ5OLwqj0jPj5ZUHMW5y0AhuazdMj1RV+Ps5fWoMWnpHSEZRWCnKuwttc
    FbcJEbdVWhszIL+H2SB9vh0CgYB+WKwhrUpPtFB6WjJq66lajsAm+hL/1y9IBG3s
    S9XL8n41roN1D3z8IV2LsZS3vrGsPZJHvekvYVnBE11tO7Iv6n6BIzu/crKVUc7g
    bxyeD7c4vY7nUtQqzzcNhPsI6E4JGVuuW3aDKIZA0eN4tGYXsLK2KgrBSiqQxQs7
    H21hAQKBgQDdu1dBbnaOpGom7TyCIGoddZAhcAKVGVH4aQVSoz+mMmzQLKtZVBID
    cCFm/4Lmzxlecczyw8DEcMfRqot1xavJT0QE2tZ4ROOgk2mcUV5D4wbRNBZxLR2M
    34ccn+oqh1LcEa9RE3QoLsIHZInRElZesQCckOru46paeHKAJsxZ9Q==
    -----END RSA PRIVATE KEY-----
  kubelet.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSk9IUVN1ZWZlS0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1UQXhPRFE0TURKYUZ3MHpOVEV4TURneE9EVXpNREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURieGdxR0xHZDE1NnN3V0NsUTVyYW11TXZ6WWE1UmRWNkE3TWtXNnFvSnk1UlNpMW8wMGNrT0JmNEwKNm9oVHlyb2pDRWt0S3F6SmYyL0RkVkxCcUxJNDBNbjgvVExmK0lnR1hCb0gzYlM0N0U5dnpUS2w4cU0yajh6ZgpZVmVTSENld0FtSkYyWDJuSlJMTlVPclgwY21KMWpydkJSUklvOHp3RFlpUTdrMk4ybmFwN2JGNGRMdElaY2cwClZaWkpMT05HWGlzME9JbUJSWndtM2lxdGdicFBtRGllNUk5cDFLZDU4Q3hmQ3EzOU8yUXFWNTJWMUF5bXp5YnEKV1JQd3hVdHIwL0oyUk94ZERLMnBmMGxNeVR4UTY4T2ZaSDFZdUkxNnVJUlY1Y0RuRkgydUNEM2hPVUdSOXBScQpuZHFQVlVmdU12L0s1aitWYXFYRkQzS0UxRFZuQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSMnY1WlA1TjR5TU9XbUxHcERDdjJtTkxJcmZUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUhnczBwR3JnUgpYSDV1UDRNbFhOaGZ0cFRaUm0wZGk4OG1SSlNBcm5vTnhpb2hzdXJOdk11VGFZQktiY2txWXpSYU5HVjRCQzhhClFUYU9QbUdEZGJqekQrMXRxaTdTMU11TXZuUFdkQW9aOCtjcjMrMENsaDI2bFVJMGErOUx2OFFQRnV6ajc2dXoKZ3JJenNCSFpkSnhXcTFpS0E3ZU1iM0lDbnpmc0o5bktpNzl1dUtYZFJlbUxEamdCMDB5VWtJOVVaZ2VOZXNUZApxNkcySEtSUVdQdG9uZnk3bXN3SXUzbVVpcUY3OFhXSFNYSUxWVDU3c3NYQ3dDMWRhMDhjVXlrcnMvWU41RGRPCkp2MmVlVGN3M1hLVHJGaEtKWUdCZU5tQWV5Rlk5UERpbldET1N3aVcxRlZpc0dES2svUE1nelVrTWw3OGNJYjgKYmFFR0pWejF0OXNXCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://10.0.0.35:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJT3VBUEpCUG5DNEF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1UQXhPRFE0TURKYUZ3MHlOakV4TVRBeE9EVXpNREphTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFERVI5V24Kalg3ZTd1YjVTck9wUnIzVTU0aTRxZmJoRmNsajlIYTZRaXRPaVBzOXNJc0h5V1AyUnRGQVVYU3JrWVFNNVpKVQo0b2dweGZuZXdpYUx0b0h4UjBCZWFpa0JYT1NRdWpkMFU1VmN6Mm0zRUJPd3REcVFZTyt0U3BnczFZbzNmUkZBCmVTZ0RqQW9peUwxMXZQRWFhT2Y1NzArcS8zbE9pMG9ReDRtNkN0YTRnbnVkcHNLRUh4RnRjdnlhZlZwU0QxM0YKWmY5VWR3TGIyeXl6b24yOHZ4amNUamxxK0xTSUl6MHpnYjR4VGxrWVVmRjJBMjlBTnZLVzZwdDZpOGk0VmRnUQpodUhmYXIzd2ZqTkRROTNRckFPSW5XajNVd2kvbWJiUXFkeUZiR21vdmgzU3l3Q2h4aUpHQW82YWlSck1XTEcrCnJ3Nll0RnhFKzkyVG5GNVpBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkhhL2xrL2szakl3NWFZcwpha01LL2FZMHNpdDlNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJCRVZUNjJNUEF6MlVJS0NnbTBMRFI1RWlDCitYbnhUZHhwZmk5MXp5UTdRZEkxWHZNdE9xMXJ4UTVIWjAwc0Q1WXVkQldidlo1aC9jUEc3TWx4cTlVbGNiNUkKanBnVHZ4YzExYmRLa2l6WUFQS00xYlYxb1puMjNXbE9TR0svS3pOQnlNNVhLdkVpdEpxVlJtdlA0ZFIySkpiTgo4OTVHVE1HRGRkeEkzUlNldVdvdDFpVzdpUFBKMDhuenVMbnZ3RkRWMVJUa0tKU3VJc1EvczNUOFU4Wlp6Q3BpCm5iY1dMdmJDYWxldTdlaHhIcFBvTHI3L3dPUzhMYnYzODhHZCtvU3IyR2MwSlN0eGRxN3ZNVFNNaHBuSzVnQnQKaUNkTlR4cDJReHUvaUx4V1YvbVE1bVkvdW5Xb0xpUklIZzhqS0owS3NFVXVXUE5KY3dRUHN6UXN1T0xNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeEVmVnA0MSszdTdtK1VxenFVYTkxT2VJdUtuMjRSWEpZL1IydWtJclRvajdQYkNMCkI4bGo5a2JSUUZGMHE1R0VET1dTVk9LSUtjWDUzc0ltaTdhQjhVZEFYbW9wQVZ6a2tMbzNkRk9WWE05cHR4QVQKc0xRNmtHRHZyVXFZTE5XS04zMFJRSGtvQTR3S0lzaTlkYnp4R21qbitlOVBxdjk1VG90S0VNZUp1Z3JXdUlKNwpuYWJDaEI4UmJYTDhtbjFhVWc5ZHhXWC9WSGNDMjlzc3M2Sjl2TDhZM0U0NWF2aTBpQ005TTRHK01VNVpHRkh4CmRnTnZRRGJ5bHVxYmVvdkl1RlhZRUliaDMycTk4SDR6UTBQZDBLd0RpSjFvOTFNSXY1bTIwS25jaFd4cHFMNGQKMHNzQW9jWWlSZ0tPbW9rYXpGaXh2cThPbUxSY1JQdmRrNXhlV1FJREFRQUJBb0lCQUFOQVExZ3Vua3JYL3loaQo1ZDNvWjQyR3RqdUV5U3VLUGxjeS9lSnc1U0c4WUJqeCt5T0tZT2I3M2t4bjdQeElnVHpyY29TSWFnUHpIUVBsCkNGbHBFUGJybkxQVG8xRTc5aWMxaG1TZFc4eDVQUUdFdVNiRW5YRzF3VktIK1VSSTF5eTdIQldLekRCZTJlNGcKa0E3S3JkMm5uaXdFSERneldoR0VlaG9VREFKeVV4VnFsQmtURHNrSk1JeEgzNmlEcVd4eG41aTVqMGdXZHJkbQpSN3I5VU9mRUNwMCtlckx5UlZVN0ExTjJ1c2g2N1Z6cUIrZFFYbkc5b1QwVjR3TzlZdDFRZkNBZjVrQjZLbFQwCmFEQ0toWENSd2J1Rlo0bUhLajdkMUIvL2IvM1pXb3hZQUx3NHluR3NsSjV4Z2x4REl4UVVGTURhUzRrUHVraEsKUzJuZ0NrRUNnWUVBMmZ6bFRVT3lRaWdCZ21rQzVCdXBmZk5NS01RNjQ5Y3NYTTB1NFlhdDVaSDZvb1dwdGRTNgozYjU2QklVTXJKMnkxSkUwajBKTC9lTTl1VTE0YjBjS1JhSmFpemFHZkM2N2RMd0NQakpScE1mSWFZcGpKMG5HCmtjb1RrT256RTBvY3QxclJHYStKQ2ZmZnZkLzcwdUd5cjBrNmtJSGsxc3JGcmVZa01IbVJuV2tDZ1lFQTVvSHAKOFR2WmFkQytCbm1xdHg4ZTN3NnZZeVZ6UlkwbkZXZDNVVnlWVjJrb21scWhPY21wTWtxekhQbnBaVCszMnVHVgpPelV2YkNZZnlhK0lqYkNGdTRWekhudmxxTEphNXRWRW5xVUFZS0pCQ2hGTVNNVFpTRi9BS214TTVlK2srYmRWCkhuK1UwaDRMSFExd2pWRHowYkkvVGZHcUs3RlZpdDk1RHREVGEzRUNnWUVBenlUL3JTVm9UbTkveDdJTVdrRmoKRmRuT0JHczhYdWhKTXNLVUN5R1ZQRE0xRFoyZ2dMWnZBR3FSdnB2RVNIL3V3UXBlL01lT09Pdm82cDZRbElYWQpZQVdBcnd1WVRvZUdBTTdyL3JpSVZ1SzJNbnliN21pdjlqZ2wwYTVQRzRSd3QxZm9uZFR0ajNocHVDQVJSL3JMCmRzQktrNm1ya09UTlpvdnMxZGVnSlFrQ2dZQW1FOHZiWjdHUWcwVUF1TlIwajVWLzcyTVZrN2dwQXhvenRQWEcKNE81aWxDSjY3UUc1RkJENUY5SGl0WDNTbGVYL0tFaUlrVTZXSk80WFdRSEx0aDlCVE5ncGJ2b1BGZmRpTGxTNQppRFE1d2xQUUgrOWtEZkIrdmlKMlg1R01ZanYwYkU2SlRUWCtSNnc2VG1BTFdCWU95ODBkU1JCOVN6d0FSczR1Cm5seHVZUUtCZ0dRWlhKNG85NlhKb1ZUZlBzYThMeEphY2M1ZEFuMk9qWkVjVER5VExXVWNKbmlPZDIvclJlN3gKd3BHdGR1WVBZaGUrbElPbmtZT1lHaVJLYWc0dzQxZmFRVlVaSnUyeHdqdkNiT2xtcml5bmp1OEtSUk1tNHFSeApJU1ZORTJ2R0VaTXIrdGsySkg2NVUzYmNMWkptUFVNSllNL1NLczFzVFBieUUxOG9kZFQ5Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbokube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: turbokube
  template:
    metadata:
      labels:
        app: turbokube
    spec:
      containers:
      - name: turbokube
        image: pantopic/turbokube
        imagePullPolicy: Always
        args:
        - /turbokube
        - --provider-config
        - /etc/turbokube/config.json
        - --provider
        - mock
        - --startup-timeout
        - 10s
        volumeMounts:
        - name: turbokube
          mountPath: /etc/turbokube
        env:
        - name: KUBELET_PORT
          value: "10250"
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APISERVER_KEY_LOCATION
          value: /etc/turbokube/apiserver.key
        - name: APISERVER_CERT_LOCATION
          value: /etc/turbokube/apiserver.crt
        - name: KUBECONFIG
          value: /etc/turbokube/kubelet.conf
      volumes:
      - name: turbokube
        configMap:
          name: turbokube
