apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    app: turbokube
spec:
  replicas: {{ .VNodes }}
  selector:
    matchLabels:
      app: {{ .Name }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
    spec:
      containers:
      - name: turbokube
        image: mirror.gcr.io/pantopic/turbokube
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 32Mi
        args:
        - /turbokube
        - --provider-config
        - /etc/turbokube/config.json
        - --provider
        - mock
        - --startup-timeout
        - 10s
        volumeMounts:
        - name: turbokube
          mountPath: /etc/turbokube
        env:
        - name: KUBELET_PORT
          value: "10250"
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APISERVER_KEY_LOCATION
          value: /etc/turbokube/apiserver.key
        - name: APISERVER_CERT_LOCATION
          value: /etc/turbokube/apiserver.crt
        - name: KUBECONFIG
          value: /etc/turbokube/kubelet.conf
        - name: VKUBELET_TAINT_KEY
          value: "{{ .Taint.Key }}"
        - name: VKUBELET_TAINT_VALUE
          value: "{{ .Taint.Value }}"
        - name: VKUBELET_TAINT_EFFECT
          value: "{{ .Taint.Effect }}"
      volumes:
      - name: turbokube
        configMap:
          name: turbokube
